### ISSUE TITLE
Create VB.NET Example

### ISSUE THREAD

**Issue by mjallday** [verygoodsecurity/vgs-proxy-examples#35]
You know the drill.

**Comment by jviveiros** [comment]
Was researching into this and I actually don't know if this makes a lot of sense. Was reading more about VB.NET and found this lil snippet on wikipedia below. My other issue is that it appears that .NET Core (the cross platform .NET framework only supports C# (from what I can tell) without paying for MS Visual Studio for Mac. I'm going to see if I can find a syntax converter based on my quoted research and see if someone on a windows machine or who has a windows VM can test it. 

> 

Though C# and VB.NET are syntactically different, that is where the differences mostly end. Microsoft developed both of these languages to be part of the same .NET Framework development platform. They are both developed, managed, and supported by the same language development team at Microsoft.[8] They compile to the same intermediate language (IL), which runs against the same .NET Framework runtime libraries.[9] . Lastly, both languages reference the same Base Classes of the .NET Framework to extend their functionality. **As a result, with few exceptions, a program written in either language can be run through a simple syntax converter to translate to the other. There are many open source and commercially available products for this task**.

>

**Comment by jviveiros** [comment]
Pull #39 Should close this but doesn't run on .NET Core (only C# and F# do) so the test can't be deployed via docker, at least without configuring a docker container using NET Framework (not the non-windows net core.
