### ISSUE TITLE
Create full Android Demo

### ISSUE THREAD

**Issue by gjyoung1974** [verygoodsecurity/vgs-proxy-examples#44]
@jviveiros @mjallday 
How about an Android "add a payment card demo?"
1 includes Card.Io scanner
2 Save a token on Mobile Backend or locally for later purchase
PR#
https://github.com/verygoodsecurity/vgs-proxy-examples/pull/45

Cheers!
~Gordon

**Comment by gjyoung1974** [comment]
it's here:
https://github.com/gjyoung1974/vgs_cardform_demo

Just need to figure out how to build Android stuff on CircleCI

**Comment by jviveiros** [comment]
Nice! I'll look into it.

**Comment by gjyoung1974** [comment]
This issue can be closed
